### PR TITLE
added local json-server

### LINKED ISSUE #35: mock environment for development
Bootstraps the dashboard in a mock environment. Even if the backend is not up and running, you can still use mock data to populate dashboard pages.

### PR DESCRIPTION
**Pull request by kunatastic**
fixes: #35

### CODE REVIEW

**Comment by kunatastic** [comment]
I have added an additional npm script to execute the local server and it shall execute on the 9990 port.

Is there anything that shall be changed?

**Comment by ruddi10** [comment]
Will have a look

**Comment by aquibbaig** [comment]
@kunatastic Thanks for this PR, it looks good more or less (I haven't tested it fully yet), can you add a rule in your IDE that adds an extra line at the end of every file and commit the changes?

Once done, you can ask for a review

**Comment by muskankhedia** [comment]
@kunatastic Could you please check the below error

**Comment by ruddi10** [comment]
> @kunatastic Could you please check the below error. I started receiving it after checking to your branch. image

@muskankhedia can you please check if we have eslint-disable on the top in utils/useFetch.ts as it was required otherwise this error was thrown

**Comment by aquibbaig** [comment]
@kunatastic I think the issue has been fixed in a latest patch, pull from master. cc: @ruddi10

**Comment by kunatastic** [comment]
Has the issue been resolved already?

**Comment by aquibbaig** [comment]
can you confirm by pulling from master?

**Pull request closed without merging**
