### PR TITLE
Use @faker-js/faker instead of faker.js

### LINKED ISSUE #43: Remove faker js and use another library
Because `What really happened with Aaron Swartz?`

### PR DESCRIPTION
**Pull request by MohdImran001**
Fixes #43 

After the faker.js repo was deleted, a new package known as community-faker was published which is exact replica of faker. However the community-faker doesn't have the `@types` declaration as of now but hopefully, it will be there in a few days.

`http://localhost:5000/` was hardcoded in e2e tests and they were failing on my system because the dashboard is using port 3000 on my system. Therefore I also added frontendBaseUrl in constants.js

### CODE REVIEW

**Review by aquibbaig — CHANGES_REQUESTED** [review]
If it is a default import, we can do something like:
```
import faker from 'community-faker'
```

This will let us not change much of the naming schemes in our app

**Comment by MohdImran001** [comment]
PTAL @aquibbaig

**Comment by ruddi10** [comment]
@MohdImran001 I don't think using localhost:5000 was a problem as its different from the local development server you run, we do e2e test for the build of react that is done by first running the command yarn build and then we serve this build using serve -s build command which serve the build on port 5000. So I request you to kindly change the code accordingly

**Comment by MohdImran001** [comment]
@ruddi10, sure, I will do it. Before running e2e tests,  we have to build the frontend. is it correct?

**Comment by ruddi10** [comment]
> @ruddi10, sure, I will do it. Before running e2e tests,  we have to build the frontend. is it correct?
> 

Yes and then serve it using the command serve -s build

**Comment by MohdImran001** [comment]
@aquibbaig PTAL

**Review by aquibbaig — APPROVED** [review]

**Review by ruddi10 — APPROVED** [review]

**Pull request merged**
